openapi: 3.0.3
info:
  title: TaskTracker log models
  description: Log models for logging services of TaskTracker
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
paths: {}

components:
  schemas:
    CommonLogModel:
      title: Общая модель лога
      description: Общая модель лога для всех микросервисов системы
      type: object
      properties:
        messageTime:
          type: string
        logId:
          type: string
        source:
          type: string
        task:
          $ref: '#/components/schemas/TrackerLogModel'
        errors:
          type: array
          items:
            $ref: '#/components/schemas/ErrorLogModel'

    TrackerLogModel:
      title: Модель лога для микросервиса TaskTracker
      type: object
      properties:
        requestId:
          type: string
        operation:
          type: string
          enum:
            - create
            - read
            - update
            - delete
            - search
            - init
            - finish
        requestTask:
          $ref: '#/components/schemas/TaskLog'
        requestFilter:
          $ref: '#/components/schemas/TaskFilterLog'
        responseTask:
          $ref: '#/components/schemas/TaskLog'
        responseTasks:
          type: array
          items:
            $ref: '#/components/schemas/TaskLog'

    ErrorLogModel:
      title: Модель лога для ошибки
      type: object
      properties:
        message:
          type: string
        field:
          type: string
        code:
          type: string
        level:
          type: string

    TaskLog:
      title: Модель лога для задачи
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        executor:
          type: string
        taskType:
          type: string
        visibility:
          type: string
        customerId:
          type: string
        permissions:
          type: array
          uniqueItems: true
          items:
            type: string

    TaskFilterLog:
      title: Модель лога фильтра
      properties:
        searchString:
          type: string
        customerId:
          type: string
        workSide:
          type: string

